### ISSUE TITLE
Incorrect match on something.....edu

### ISSUE THREAD

**Issue by IlyaSemenov** [ljosa/urlize.js#23]
This is clearly a bug:

```
> require('urlize.js')('something.....edu')
'<a href="http://something.....edu">something.....edu</a>'
```

Exactly one consecutive dot should be allowed in the URL.

**Comment by IlyaSemenov** [comment]
The is caused by lots of my real users' input, for example: "You start small....baby steps."

I am using all TLDs for urlize, and `.baby` is a valid TLD (see [tlds](https://github.com/stephenmathieson/node-tlds/blob/6854984eec0aad71ce14ee9fb33b0a53c0b6c170/index.js#L101)). This results in:

```
> require('urlize.js')('You start small....baby steps.', { top_level_domains: require('tlds') })
'You start <a href="http://small....baby">small....baby</a> steps.'
```

The fix doesn't break any of the prior unit tests, so I assume it's backwards-compatible. Granted, I never validated it against Django.

**Comment by ljosa** [comment]
Thanks, that makes good sense. I'll take a close look.

**Comment by IlyaSemenov** [comment]
I concur that Django 1.11 suffers from the same problem:

```ipython
In [1]: from django.template.defaultfilters import urlize

In [2]: urlize('something....edu')
Out[2]: '<a href="http://something....edu" rel="nofollow">something....edu</a>'
```

So I agree the fix should indeed be applied only when django_compatible is false.
